baseURL = 'https://wenkai777.github.io/ArchiveOfMysteries/'
languageCode = 'en-us'
title = 'Archive Of Mysteries'
theme = 'type-writer'

canonifyURLs = true
relativeURLs = false

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[[menus.main]]
  name = 'Posts'
  pageRef = '/posts'
  weight = 1

[[menus.main]]
  name = 'Contact'
  pageRef = '/contact.md'
  weight = 2